### ISSUE TITLE
Synopsis

### ISSUE THREAD

**Issue by EloMonarch** [darenliang/mal-api#10]
Hmm why doesnt the synopsis print the whole thing? It prints some lines then stops.. and puts "..." at the end of the sentence

**Comment by darenliang** [comment]
Could you provide a code sample?

**Comment by EloMonarch** [comment]
print(anime.results[0].synopsis)
for the search (tokyo ghoul √A) prints "Ken Kaneki has finally come to accept the monstrous, flesh-craving part of himself that he has feared and despised for so long. After escaping captivity and torture, Kaneki joins Aogiri Tree—the very..."

**Comment by darenliang** [comment]
That is an issue with how mal display their synopses through search.

Search might not give you the complete information you need so you might have to get the ID and use `Anime` instead.

**Comment by EloMonarch** [comment]
is there a way to find the id through animesearch?

**Comment by darenliang** [comment]
Try `.mal_id`.

**Comment by EloMonarch** [comment]
that worked! Thank you!
