### ISSUE TITLE
Add character search

### ISSUE THREAD

**Issue by rajiv143** [darenliang/mal-api#12]
Hi, I use your api for my discord bot.
Very simple API.
It would be pretty cool if you could add character search or some sort of character info.

Like get character from anime.mal_id
Also if you could get the birthdays of the characters?
Would be pretty cool.

Thank you.

**Comment by darenliang** [comment]
Hi rajiv143,

Character search/info can be added, but it'll require a bunch of dev work.

If you require the feature in the near future I would suggest using Jikan API (https://jikan.moe/) which provides this kind of functionality.

**Comment by darenliang** [comment]
A small update, basic character info has been added to Anime and Manga a while ago.
