### ISSUE TITLE
New characters not working with all animelist pages

### ISSUE THREAD

**Issue by binsento42** [darenliang/mal-api#16]
There are some changes in the refactored code that make it behave differently than the original code in the character branch and return empty list, while the original branch did not return empty. This happens i.e. with id 4063 and appears to be quite rare, I haven't found another id yet (except the related 5277) so it is pure coincidence that I discovered this.

**Comment by darenliang** [comment]
Thank you for finding this. It turns out for anime and manga that have items on sale the page structure changes.

The fix also fixes the `.related_anime` and `.related_manga` properties and it isn't pretty, I'll see what can be done to make it less janky.
