### ISSUE TITLE
Feature Request - Updated Episodes Watched

### ISSUE THREAD

**Issue by wahab14131211** [darenliang/mal-api#17]
Would it be possible to add a feature to login to MAL, and update the number of episodes watched?

**Comment by darenliang** [comment]
It could definitely be possible. There is still a lot to implement for the public API, so I don't think supporting auth is a priority right now.

You could check this: https://github.com/jikan-me/jikan-auth, but unfortunately, you'll need to self-host it.

I'll keep this issue open in case there are any updates.

**Comment by wahab14131211** [comment]
Looks like the jikan-auth is a little too advanced for me at this time, but thank you for the quick response!
Even with the already implemented features, this is an awesome API!

**Comment by darenliang** [comment]
No problem!
