### ISSUE TITLE
No Popularity and Rank in Search

### ISSUE THREAD

**Issue by Technoselbow** [darenliang/mal-api#18]
when i try to implement a search, there are no rank or popularity attributes. please add this

**Comment by darenliang** [comment]
Rank and popularity aren't exposed by Search. The recommended way is to use Search to get the id and then query Anime using that id.

```py
from mal import Anime
from mal import AnimeSearch

search = AnimeSearch("cowboy bebop")
mal_id = search.results[0].mal_id

anime = Anime(mal_id)
print(anime.rank)           # rank
print(anime.popularity)     # popularity
```
