### ISSUE TITLE
Genres list empty for listings with only one genre

### ISSUE THREAD

**Issue by binsento42** [darenliang/mal-api#19]
I haven't been able to investigate yet if this is new behaviour (due to site changes), but I have been able to connect the empty genre lists I've been getting lately to listings that have only 1 genre. This could be a coincidence, but it doesn't look like it. Maybe this has always been an issue, but were listings with only 1 genre fairly uncommon and haven't I noticed this before.

**Comment by darenliang** [comment]
Could you provide any code samples that can replicate the issue?

**Comment by binsento42** [comment]
from mal import Anime

# Visual Prison has genre 'Supernatural'
anime = Anime(48567)
print(f"Genre of {anime.title} is {anime.genres}")
# 86 Part2 has genres 'Action, Drama, Sci-Fi'
anime = Anime(48569)
print(f"Genre of {anime.title} is {anime.genres}")

**Comment by binsento42** [comment]
from mal import Anime

''' Visual Prison has genre 'Supernatural' '''
anime = Anime(48567)
print(f"Genre of {anime.title} is {anime.genres}")
''' 86 Part2 has genres 'Action, Drama, Sci-Fi' '''
anime = Anime(48569)
print(f"Genre of {anime.title} is {anime.genres}")

**Comment by darenliang** [comment]
Thanks, I'll look into it soon.

**Comment by darenliang** [comment]
This issue should now be fixed.
