### ISSUE TITLE
Feedback on how to implement search functionality

### ISSUE THREAD

**Issue by darenliang** [darenliang/mal-api#3]
Without search, this library is practically useless.

Any feedback on how to implement search functionality is greatly appreciated.

There are a few questions:

1. How should the response be structured?
2. How should the search function signature be like?

**Comment by collinarnett** [comment]
I don't know how useful those 50x70 icons that comes from the search results. I used some regex to give the full sized image from the image url:
```python
re.sub('r\/50x70\/|\\?s=.*','', image_url)
```

**Comment by darenliang** [comment]
Sounds good! I'll take a look at it.

**Comment by collinarnett** [comment]
It would also be great to be able to get the synonyms for the searched manga/anime.

**Comment by darenliang** [comment]
There's still a bunch of fields/attributes that aren't parsed such as staff and characters, however, if I recall correctly, synonyms might not be available from MyAnimeList's search pages.

It might be available from the official MyAnimeList Beta API which came out earlier this year.
