### ISSUE TITLE
Seasonal Anime

### ISSUE THREAD

**Issue by bae-hul** [darenliang/mal-api#6]
A way to view all the currently airing anime would be nice =)

**Comment by darenliang** [comment]
Hi @bae-hul,

I'll look into it. My guess is that it'll look very similar to Jikan's interface.

**Comment by bae-hul** [comment]
Oh i actually worked on it myself today.
Quite simple using just requests module

**Comment by darenliang** [comment]
That's great!

**Comment by darenliang** [comment]
Should I keep this issue up or should I close it for now?

**Comment by darenliang** [comment]
I'll close this for now. Feel free to open up the issue again.
