### ISSUE TITLE
New feature request: mal_id as member from AnimeSearch

### ISSUE THREAD

**Issue by binsento42** [darenliang/mal-api#8]
I think that AnimeSearch should also have a mal_id member, as to feed in the Anime class. A logical usage for the api would be:
search = AnimeSearch(someTitle)
#pickCorrectResult
anime = Anime(search.results[x].mal_id)
#dosomestuff with anime members..

It is off course possible to retrieve the id from the url (as I've done so far) but it is a bit of a strange workflow, it would make more sense if search made it available.

**Comment by darenliang** [comment]
You are totally right. Search should include IDs.

I will look into it soon.

**Comment by darenliang** [comment]
Commit a987fc2 should include mal_id.

The newest package version is v0.3.1.

**Comment by binsento42** [comment]
Thanks again for the quick fix. I've already tested it.
